ro_tax_match = {
    "TVA Taxare Inversa": "Inverse Taxation Deliveries",
    "TVA Taxare Inversa 0%": "TVA Taxare Inversa Achizitii 0%",
    "TVA Taxare Inversa 5%": "TVA Taxare Inversa Achizitii 5%",
    "TVA Taxare Inversa 9%": "TVA Taxare Inversa Achizitii 9%",
    "TVA Taxare Inversa 19%": "TVA Taxare Inversa Achizitii 19%",
    "TVA Taxare Neimpozabila Livrari": "TVA Taxare Intracomunitara Neimpozabila Livrari",
    "TVA Taxare Neimpozabila Achizitii": "TVA Taxare Intracomunitara Neimpozabila Achizitii",
    "TVA colectat 0% Bunuri": "TVA Colected 0%",
    "TVA colectat 5% Bunuri": "VAT Colected 5%",
    "TVA colectat 9% Bunuri": "VAT Colected 9%",
    "TVA colectat 19% Bunuri": "VAT Colected 19%",
    "TVA deductibil 0% Bunuri": "TVA deductibil 0%",
    "TVA deductibil 5% Bunuri": "TVA deductibil 5%",
    "TVA deductibil 9% Bunuri": "TVA deductibil 9%",
    "TVA deductibil 19% Bunuri": "TVA deductibil 19%",
    "TVA Taxare Scutita Livrari cu drept de deducere": "TVA Taxare Scutita Livrari",
    "TVA Taxare Scutita Achizitii Intracomunitare": "TVA Taxare Scutita Achizitii",
    "TVA Intracomunitara Livrari Bunuri": "Intra Community VAT Deliveries",
    "TVA Intracomunitara Achizitii 0% - Bunuri": "TVA Intracomunitara Achizitii 0%",
    "TVA Intracomunitara Achizitii 5% - Bunuri": "TVA Intracomunitara Achizitii 5%",
    "TVA Intracomunitara Achizitii 9% - Bunuri": "TVA Intracomunitara Achizitii 9%",
    "TVA Intracomunitara Achizitii 19% - Bunuri": "TVA Intracomunitara Achizitii 19%",
}
